spring.application.name=service-consultant
server.port=8082
spring.data.mongodb.uri=mongodb://localhost:27017/test

jwt.secret=ma-cle-secrete-de-projet-tres-longue-au-moins-32-caracteres
jwt.expiration-ms=86400000