spring.application.name=service-notification
server.port=8085
spring.data.mongodb.uri=mongodb://localhost:27017/test

jwt.secret=ma-cle-secrete-de-projet-tres-longue-au-moins-32-caracteres
jwt.expiration-ms=86400000

firebase.service-account-path=firebase-service-account.json