spring.application.name=service-user
server.port=8081

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://consulting-admin:test@consulting-platform.f4skgra.mongodb.net/service-user?retryWrites=true&w=majority&appName=consulting-platform
spring.data.mongodb.database=service-user

# Firebase
firebase.project-id=android-project-2e4bb
firebase.service-account-path=firebase-service-account.json

# JWT
jwt.secret=ma-cle-secrete-de-projet-tres-longue-au-moins-32-caracteres
jwt.expiration-ms=86400000

# Logging
logging.level.org.springframework.security=DEBUG


# Disable CORS on service-user since gateway handles it
spring.web.cors.enabled=false


logging.level.com.consulting=DEBUG
server.error.include-message=always
server.error.include-binding-errors=always