spring.application.name=service-user
server.port=8081
spring.data.mongodb.uri=mongodb://localhost:27017/test
firebase.project-id=consulting-ai-platform
firebase.service-account-path=firebase-service-account.json

jwt.secret=ma-cle-secrete-de-projet-tres-longue-au-moins-32-caracteres
jwt.expiration-ms=86400000